/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("OrdersObjectPageObjectPage journey");

        opaTest("Navigate to OrdersObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheOrdersList.onFilterBar().iExecuteSearch();

            Then.onTheOrdersList.onTable().iCheckRows();
            When.onTheOrdersList.onTable().iPressRow(0);

            Then.onTheOrdersObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheOrdersObjectPage.iCheckNumberOfSections(2);
            When.onTheOrdersObjectPage.iPressSectionIconTabFilterButton("FieldGroup::General");
            Then.onTheOrdersObjectPage.iCheckSection({ section: "FieldGroup::General" });
            Then.onTheOrdersObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "orderDate" });
            Then.onTheOrdersObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "customer_ID" });
            When.onTheOrdersObjectPage.iPressSectionIconTabFilterButton("items::LineItem");
            Then.onTheOrdersObjectPage.iCheckSection({ section: "items::LineItem" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});